export enum EstadoSolicitud {
  EN_REVISION = 'EN_REVISION',
  APROBADA_COMISION = 'APROBADA_COMISION',
  APROBADA_DIRECCION = 'APROBADA_DIRECCION',
  RECHAZADA_COMISION = 'RECHAZADA_COMISION',
  RECHAZADA_DIRECCION = 'RECHAZADA_DIRECCION',
  EN_ESPERA = 'EN_ESPERA',
}
