export enum RolUsuario {
  SOLICITANTE = 'SOLICITANTE',
  FUNCIONARIO_MUNICIPAL = 'FUNCIONARIO_MUNICIPAL',
  COMISION_OTORGAMIENTO = 'COMISION_OTORGAMIENTO',
  DIRECTOR_CIRCULO = 'DIRECTOR_CIRCULO',
  ADMINISTRADOR = 'ADMINISTRADOR',
}
